### PR TITLE
Fix bash_unit - most shellcheck messages

### PR DESCRIPTION
**Pull request by mdeweerd**
# Fix bash_unit - most shellcheck messages

Fixes in bash_unit to compensate for most shellcheck message except some case where more analysis is needed.

### CODE REVIEW

**Comment by pgrange** [comment]
Hi @mdeweerd ,

I just ran the test on this branch and they fail. I must admit I did not spend time looking into it yet to figure out what the problem is but I've noticed that the following test will fail:

```bash
./bash_unit tests/test_doc.sh 
```

It's related to some string formatting I think so, I guess there are some `'` or `"` or `\` change that you're proposing that is having an impact on this. Will try to take a look later in the week.

Cheers,

**Comment by mdeweerd** [comment]
I rebased this PR with my tricks so that it now incorporates the spelling.

This works on my PC (cygwin!), and also in ci (https://github.com/mdeweerd/bash_unit/actions/runs/7899681189 ).

**Comment by pgrange** [comment]
Ok, for some reason the test claim to pass but, unfortunately, they silently fail. Look for [FAILURE](https://github.com/mdeweerd/bash_unit/actions/runs/7899681189/job/21559640330#step:3:132) in the ci execution.

**Comment by pgrange** [comment]
It looks like it's coming from f9965082ca11733152a4b67721fc304e6d8dbbc3. If you just drop this commit, test are passing again.

**Comment by mdeweerd** [comment]
I thought that the FAILURE was part of a test .

I dropped that commit from this PR and created #102 which includes it (on top of the commits that are kept here).

A local error I get without the commit is:
```
sed: couldn't open file //tmp/58592/swap: No such file or directory
```

So the dropped commit needs further splitting I guess to understand what is generating the issue.

**Comment by mdeweerd** [comment]
Here is the output after setting
``` bash
#!/usr/bin/env -S bash -x
```
[error.txt](https://github.com/pgrange/bash_unit/files/14349901/error.txt)

I made changes to fix this error in #102 .

**Pull request merged**
