### PR TITLE
Fix shellcheck messages

### PR DESCRIPTION
**Pull request by mdeweerd**
This is the continuation of #99 where I dropped the commit that made the tests fail so that this dropped commit can be examined independently.

### CODE REVIEW

**Comment by pgrange** [comment]
So this is crazy to me:

|                               | PR #99              | PR #102          |
|------------------| --------------- | -------------- |
| @pgrange env.    | ✅ test passes | ❌ test fails     |
| @mdeweerd env | ❌test fails       | ✅test passes |

Here is how I run the test:

```bash
docker run -v $PWD:/bash_unit debian /bash_unit/bash_unit /bash_unit/tests/test_cli.sh /bash_unit/tests/test_core.sh /bash_unit/tests/test_doc.sh /bash_unit/tests/test_tap_format
```

Could you share with me the system, version of bash or whatever information on the environment where you run the tests because I'd like to reproduce the error you see (_ sed: couldn't open file //tmp/64451/swap: No such file or directory_) locally to understand what's going on.

**Comment by mdeweerd** [comment]
I found it for sed:

```
  /^```$/ , $ w//tmp/12679/swap
```

The '/' just after 'w' is not ok.

**Comment by pgrange** [comment]
Awesome! Now the tests in this PR also work on my machine 🎉 

The next big thing for me would be to get rid of the `_find_file` function. I don't see why you would need it.

*bash_unit* is supposed to set the current working directory to the one containing the test file. So when you run `tests/test_doc.sh` you're inside the `tests` directory. Then, if you look at the end of _test_doc.sh_ you can see that we go one directory up:

```
# change to bash_unit source directory since we should be in
# test subdirectory
cd ..
prepare_tests
```

So README.adoc is in the current working directory and so you should not have to search for it with this `_find_file` function.

**Comment by mdeweerd** [comment]
> The next big thing for me would be to get rid of the `_find_file` function. I don't see why you would need it.

```bash
$ tests/test_doc.sh 
cat: README.adoc: No such file or directory
```

**Comment by mdeweerd** [comment]
This takes "ages" on my machine:
```
++ cat /cygdrive/d/mdeweerd/workspace/bash_unit//README.adoc
++ grep -E '^```test$' /tmp/35178/remaining
++ (( ++block ))
++ run_doc_test /tmp/35178/remaining /tmp/35178/swap
++ sed '$a\'
++ work_around_github_action_problem
++ grep -v '^/usr/bin/grep: write error: Broken pipe$'
```

**Comment by pgrange** [comment]
> I like to run my scripts from any location.

Indeed, so do I. That's exactly why bash_unit takes care of always setting the current working directory to the test file directory. That way you can run your test script from any location and it just work.

So what I want to say is that it should work from any location already, without having to introduce this new function. Maybe there's an issue with Cygwin or something that's worth fixing.

**Comment by pgrange** [comment]
Hold on!

What if you run the following command:
```
./bash_unit tests/test_doc.sh 
```

**Comment by pgrange** [comment]
> And I am not that "it's not supposed to" kind of guy ...

Ok, I see how you can make it so that `test_doc.sh` could run as a standalone. It is just that here, in this context, `test_doc.sh` is a test that is supposed to be run with `bash_unit`.

I do not intend to make it any different. Especially as to make it run alone, we would have to introduce this new `find_file` function and I don't want to maintain these lines of code if I don't need it. And it is my opinion that it is not needed.

I mean, your contribution is great, I'm just not interested in `find_file` as I don't see the value in the bash_unit code base to run `test_doc.sh` without bash_unit.

Cheers,

**Comment by mdeweerd** [comment]
I removed the _find_file stuff and it does not find the README.adoc - I do not know what brakes this (at this time)

**Comment by mdeweerd** [comment]
I had README_ADOC as a variable and I just removed the quotes not adding a dot again.
This is restored now.

**Comment by pgrange** [comment]
Awesome, thank you.

**Pull request merged**
