### PR TITLE
add Tap plan to tap output

### PR DESCRIPTION
**Pull request by MichaelBitard**
For issue #31 

I did the least change possibles so http://instanttap.appspot.com/ can validate the tap format

### CODE REVIEW

**Comment by pgrange** [comment]
Hi,

Thank you for this pull request.

See my comment in #31. This pull request won't work as you expect in the case of several test files.

I suggest you add a test where bash_unit is called with two test files as parameter. With your implementation, that would lead to an issue where a first, partial, plan is displayed on the first line and then, a second partial plan is displayed in the middle of the output.

I suggest that you display the plan at the end of the test, when you know how many tests have been run. I tried and instanttap supports displaying the plan on the last line.

**Comment by MichaelBitard** [comment]
You're right about that, I'll update this, thanks

**Comment by pgrange** [comment]
Hi, 

Did you have time to look into this ?

**Comment by MichaelBitard** [comment]
Absolutely...... not.

Sorry, we are using directly bash_unit from my PR, and I didn't touch any
production bash since. But as soon as I do prod bash again, this is on my
top list.

Le mer. 29 mars 2017 à 11:51, Pascal Grange <notifications@github.com> a
écrit :

**Comment by pgrange** [comment]
No problem. Just wandering. 

I'll take a look if I find some time. 

Regards,

**Comment by MichaelBitard** [comment]
I think we can close it now.

I have a new rule of thumb. As soon as I need to write some unit tests in bash, I rewrite everything in python :)

**Pull request closed without merging**
