### PR TITLE
ADD: documentation update (initial manpage and reference to archlinux…

### PR DESCRIPTION
**Pull request by n0vember-**
… packaging)

I've created a basic manpage. Testing functions are not described yet. This manpage will be installed with the archlinux package after (if) pull request is validated.

I didn't install the manpage with the install.sh script, because either this script is too ugly, either I don't understand its beauty. Anyway, I don't know what to do with a manpage within this script.

Also a reference is made to archlinux package in README.md

### CODE REVIEW

**Comment by pgrange** [comment]
Thanks @n0vember (pretending I didn't read the comment about install.sh),

I don't like the idea of including a .gz file in the source repository. 

I am not fluent in writing man pages so not sure why you need a gzipped file but can you think of an alternative way to do that? 

Take a look at the release script at the root of bash_unit. Do you think we can include something in there to generate that gzip file when releasing? 

Or may be rely on the hidden beauty of install.sh to gzip something at installation time? 

Regards,

**Comment by pgrange** [comment]
By the way, I wanted to cherry-pick your README.md contribution about archlinux but you made one single commit for both changes: README and man.gz

Could you split both changes in separate commits ?

Regadrs,

**Comment by pgrange** [comment]
Also, it seems makepkg will implicitly gzip man pages:

https://bbs.archlinux.org/viewtopic.php?id=115415

**Comment by n0vember-** [comment]
Install.sh does install of bash_unit in the current directory, isn't it? So what is it supposed to do with the man page? 

I will split the two and unzip the man. Didn't know about makepkg zipping the man page.

**Comment by n0vember-** [comment]
Closing this pull request, and will make two clean ones.

**Pull request closed without merging**
